package ar.edu.untdf.monedas.vistas;


import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

import ar.edu.untdf.monedas.modelos.ExchangeOpen;

/**
 * @web http://jc-mouse.blogspot.com/
 * @author  Mouse
 */
public class Interfaz extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form formpadre */
    public Interfaz() {
        initComponents();
        this.setTitle("Administracion de Divisas");   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        cmdUsuarios = new javax.swing.JButton();
        cmdMonedas = new javax.swing.JButton();
        cmdCotizaciones = new javax.swing.JButton();
        cmdConsultas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        cmdUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/depa.png"))); // NOI18N
        cmdUsuarios.setText("USUARIOS");
        cmdUsuarios.setFocusable(false);
        cmdUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDepaActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdUsuarios);

        cmdMonedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/herra.png"))); // NOI18N
        cmdMonedas.setText("MONEDAS");
        cmdMonedas.setFocusable(false);
        cmdMonedas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdMonedas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHerraActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdMonedas);

        cmdCotizaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/secc.png"))); // NOI18N
        cmdCotizaciones.setText("COTIZACIONES");
        cmdCotizaciones.setFocusable(false);
        cmdCotizaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdCotizaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdCotizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeccActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdCotizaciones);

        cmdConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pres.png"))); // NOI18N
        cmdConsultas.setText("CONSULTAS");
        cmdConsultas.setFocusable(false);
        cmdConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdConsultas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrestaActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDepaActionPerformed
        if(estacerrado(usu2)){
        	usu2 = new Usuarios();
            panel.add(usu2);        
            usu2.show();
        }
        else{
            JOptionPane.showMessageDialog(this,mensaje);
        }         
    }//GEN-LAST:event_cmdDepaActionPerformed

    private void cmdHerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHerraActionPerformed
      /*if(estacerrado(ther)){
            ther = new therramienta();
            panel.add(ther);        
            ther.show();
        }
        else{
            JOptionPane.showMessageDialog(this,mensaje);
        }  */      
    }//GEN-LAST:event_cmdHerraActionPerformed

    private void cmdSeccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeccActionPerformed
        if(estacerrado(mon)){
        	mon = new Monedas(new ExchangeOpen());
            panel.add(mon);        
            mon.show();
        }
        else{
            JOptionPane.showMessageDialog(this,mensaje);
        }        
    }//GEN-LAST:event_cmdSeccActionPerformed

    private void cmdPrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrestaActionPerformed
        /*if(estacerrado(tpre)){
            tpre = new tprestamo();
            panel.add(tpre);        
            tpre.show();
        }
        else{
            JOptionPane.showMessageDialog(this,mensaje);
        }  */      
    }//GEN-LAST:event_cmdPrestaActionPerformed

//METODO QUE DEVUELVE UN VALOR BOOLEAN PARA SABER SI UN JINTERNALFRAME ESTA ABIERTO O NO
public boolean estacerrado(Object obj){
    JInternalFrame[] activos=panel.getAllFrames();
    boolean cerrado=true;
    int i=0;
    while (i<activos.length && cerrado){
	if(activos[i]==obj){
		cerrado=false;
	}
	i++;
    }
    return cerrado;
}
    /**
     * @param args the command line arguments
     */

    Usuarios usu2;     
    Monedas mon;
    
    String mensaje="¡La ventana ya esta abierta!";
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    private javax.swing.JButton cmdUsuarios;
    private javax.swing.JButton cmdMonedas;
    private javax.swing.JButton cmdConsultas;
    private javax.swing.JButton cmdCotizaciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables
    
}
